const svgOptions = { // NOTE: We have to disable most of the SVGO plugins (see: https://github.com/svg/svgo) because they cause rendering problems with some of our icons
  svgoConfig: {
    plugins: [
      { cleanupAttrs: false },
      { inlineStyles: false },
      { removeDoctype: false },
      { removeXMLProcInst: false },
      { removeComments: false },
      { removeMetadata: false },
      { removeTitle: false },
      { removeDesc: false },
      { removeUselessDefs: false },
      { removeEditorsNSData: false },
      { removeEmptyAttrs: false },
      { removeHiddenElems: false },
      { removeEmptyText: false },
      { removeEmptyContainers: false },
      { removeViewBox: false },
      { cleanupEnableBackground: false },
      { minifyStyles: false },
      { convertStyleToAttrs: false },
      { convertColors: false },
      { convertPathData: false },
      { convertTransform: false },
      { removeUnknownsAndDefaults: false },
      { removeNonInheritableGroupAttrs: false },
      { removeUselessStrokeAndFill: false },
      { removeUnusedNS: false },
      { cleanupIDs: false },
      { cleanupNumericValues: false },
      { moveElemsAttrsToGroup: false },
      { moveGroupAttrsToElems: false },
      { collapseGroups: false },
      { mergePaths: false },
      { convertShapeToPath: false },
      { convertEllipseToCircle: false },
    ],
  },
};

export {
  svgOptions,
};
