name: Merge PR

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  merge-PR:
    name: Deploy static Storybook
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    env:
      working-dir: ./
      TOKEN: ${{ secrets.GITHUBTOKEN }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
        working-directory: ${{ env.working-dir }}
      - run: npm run deploy-storybook-ci
        working-directory: ${{ env.working-dir }}
