name: Node.js CI

on:
  pull_request:
    branches:
      - master
      - next

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    env:
      working-dir: ./
      TOKEN: ${{ secrets.GITHUBTOKEN }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
        working-directory: ${{ env.working-dir }}
      - run: npm run prepare --if-present
        working-directory: ${{ env.working-dir }}
      - run: npm run lint
        working-directory: ${{ env.working-dir }}
        env:
          CI: true
      - run: npm test
        working-directory: ${{ env.working-dir }}
        env:
          CI: true
